#!/bin/bash

APP_NAME="Magnus"
DOWNLOAD="downloadGames"
EVALUATE="evaluateGames"

ENV_FILE=~/${APP_NAME}/app/.env
if [ -f "$ENV_FILE" ]; then
  source "$ENV_FILE"
fi
LOGFILE="${LOGFILE:-/tmp/${APP_NAME}.log}"

get_magnus_pid() {
    pgrep -f "node ${APP_NAME,,}.js" | head -n 1
}

get_download_pid() {
   pgrep -f "node ${DOWNLOAD}.js" | head -n 1 
}

get_evaluate_pid() {
   pgrep -f "node ${EVALUATE}.js" | head -n 1  
}

start() {
  echo "Starting $APP_NAME"
  cd ~/${APP_NAME}/app/ || exit 1

  nohup node ${APP_NAME,,}.js >> "$LOGFILE" 2>&1 &
  new_pid=$!
  echo "${APP_NAME} started in the background (PID: ${new_pid})"

  #--------------------------
  echo "Starting $DOWNLOAD"
  cd ~/${APP_NAME}/scripts/ || exit 1

  nohup node ${DOWNLOAD}.js >> "$LOGFILE" 2>&1 &
  new_pid=$!
  echo "${DOWNLOAD} started in the background (PID: ${new_pid})"

  #--------------------------
  echo "Starting $EVALUATE"
  cd ~/${APP_NAME}/scripts/ || exit 1

  nohup node ${EVALUATE}.js >> "$LOGFILE" 2>&1 &
  new_pid=$!
  echo "${EVALUATE} started in the background (PID: ${new_pid})"

}

stop () {
  local pid=$(get_magnus_pid)
  if [ -z "$pid" ]; then
    echo "${APP_NAME} is not running."
  else
    echo "Stopping ${APP_NAME} (PID: $pid)..."
    kill "$pid"
  fi
  #--------------------------
  local pid=$(get_download_pid)
  if [ -z "$pid" ]; then
    echo "${DOWNLOAD} is not running."
  else
    echo "Stopping ${DOWNLOAD} (PID: $pid)..."
    kill "$pid"
  fi
  #--------------------------
  local pid=$(get_evaluate_pid)
  if [ -z "$pid" ]; then
    echo "${EVALUATE} is not running."
  else
    echo "Stopping ${EVALUATE} (PID: $pid)..."
    kill "$pid"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    PID=$(get_magnus_pid)
    if [ -n "${PID}" ]; then
      echo "${APP_NAME}  is running in the background (PID: ${PID})"
    else
      echo "${APP_NAME}  is not running."
    fi
    #--------------------------
    PID=$(get_download_pid)
    if [ -n "${PID}" ]; then
      echo "${DOWNLOAD}  is running in the background (PID: ${PID})"
    else
      echo "${DOWNLOAD}  is not running."
    fi
    #--------------------------
    PID=$(get_evaluate_pid)
    if [ -n "${PID}" ]; then
      echo "${EVALUATE}  is running in the background (PID: ${PID})"
    else
      echo "${EVALUATE}  is not running."
    fi
    ;;
  *)
    echo "magnus {start, stop, restart, status}"
    ;;
esac



