#!/bin/bash

APP_NAME="Magnus"
APP_JS="${APP_NAME,,}.js"

get_magnus_pid() {
    pgrep -f "node ${APP_NAME,,}.js" | head -n 1
}

start() {
  echo "Starting $APP_NAME"
  cd ~/${APP_NAME}/app/ || exit 1

  nohup node ${APP_JS} >> /tmp/${APP_NAME}.log 2>&1 &
  new_pid=$!
  echo "${APP_NAME} started in the background (PID: ${new_pid})"
}

stop () {
  local pid=$(get_magnus_pid)
  if [ -z "$pid" ]; then
    echo "${APP_NAME} is not running."
    return
  fi
  echo "Stopping $name (PID: $pid)..."
  kill "$pid"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    PID=$(get_magnus_pid)
    if [ -n "${PID}" ]; then
      echo "${APP_NAME}  is running in the background (PID: ${PID})"
    else
      echo "${APP_NAME}  is not running."
    fi
    ;;
esac


